// CREATE, PAUSE, RESUME, ALTER, and CANCEL.
// SHOW CHANGEFEED JOBS

// TODO - MAKE A COCKROACHDB PACAKGE FOR :
// 1. TABLE CREATION + SCHEMA MIGRATIONS
// 2. CHANGEFEEDS subscription
// 3. changefeeds processing
