import { mkdir } from "node:fs/promises"
import { join } from "node:path"
import { build, file } from "bun"

import type { OrmDialectType } from "../../../orm/config.js"
import { letsync_schema as letsync_schema_raw } from "./letsync-schema.js"

export async function generateSchema(props: {
  source: {
    dialect: (typeof OrmDialectType)["infer"]
    path: string
  }
  target: {
    dialect: (typeof OrmDialectType)["infer"]
    dir: string
  }
}) {
  const { source, target } = props
  await mkdir(target.dir, { recursive: true })
  console.log(
    `🔄 Generating schema in "${target.dir}" [${source.dialect} -> ${target.dialect}]...`
  )

  const build_output = await build({
    banner: "// This file is generated by letsync. Do not edit it manually.",
    entrypoints: [source.path],
    format: "esm",
    minify: false,
    packages: "external",
    sourcemap: "none",
    splitting: false,
    target: "node"
  })
  const schema_raw = await build_output.outputs[0].text()
  const schema = convertSchema({
    content: schema_raw,
    sourceDialect: source.dialect,
    targetDialect: target.dialect
  })
  await file(join(target.dir, "index.js")).write(schema)

  const letsync_schema = convertSchema({
    content: letsync_schema_raw,
    sourceDialect: "cockroach",
    targetDialect: target.dialect
  })
  await file(join(target.dir, "letsync.js")).write(letsync_schema)

  console.log("\n✅ Schema conversion complete!")
}

function convertSchema(props: {
  content: string
  targetDialect: (typeof OrmDialectType)["infer"]
  sourceDialect: (typeof OrmDialectType)["infer"]
}): string {
  let { content, targetDialect, sourceDialect } = props

  const dialects = {
    cockroach: {
      enum: "cockroachEnum",
      module: "cockroach-core",
      schema: "cockroachSchema",
      table: "cockroachTable"
    },
    postgresql: {
      enum: "pgEnum",
      module: "pg-core",
      schema: "pgSchema",
      table: "pgTable"
    }
    // TODO: Find data types that are not convertable
  }

  const srcProps = dialects[sourceDialect]
  const targetProps = dialects[targetDialect]

  content = content.replace(
    new RegExp(`\\b${srcProps.enum}\\b`, "gmi"),
    targetProps.enum
  )
  content = content.replace(
    new RegExp(`["']drizzle-orm\\/${srcProps.module}["']`, "gmi"),
    `"drizzle-orm/${targetProps.module}"`
  )
  content = content.replace(
    new RegExp(`\\b${srcProps.schema}\\b`, "gmi"),
    targetProps.schema
  )
  content = content.replace(
    new RegExp(`\\b${srcProps.table}\\b`, "gmi"),
    targetProps.table
  )

  return content
}
